name: main

on:
  release:
    types: [created]
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  main:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        architecture:
        - x86
        - x64
        - arm64
        compiler:
        - vs2019

    steps:

    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: build
      shell: pwsh
      run: |
        cd libiconv
        git apply ..\libiconv.patch
        cd ..
        Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
        install-module pscx -scope CurrentUser -AllowClobber
        $x64param = if ('${{ matrix.architecture }}' -eq 'x64') { $true } else { $false }
        $arm64param = if ('${{ matrix.architecture }}' -eq 'arm64') { $true } else { $false }
        $vs2008param = if ('${{ matrix.compiler }}' -eq 'vs2008') { $true } else { $false }
        pwsh .\build.ps1 -x64:$x64param -arm64:$arm64param -vs2008:$vs2008param

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: libraries.zip
        path: dist/*.zip
        if-no-files-found: ignore

    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.zip
